### ISSUE TITLE
Reconnection issues

### ISSUE THREAD

**Issue by turnn** [Volst/laser-dac#79]
Hey guys, two developers here working on a little project, we're more than happy to spend a bit of time to get the library working and make a pull request but it'd be great if you could perhaps point us in the right direction cause we've already spent a few hours debugging this.
Significant issues with the dropout happening, I've printed out the responses from the DAC below.
The issue is the constant disconnection on Invalid response, which I'm sure you were once aware of as it is commented in the code as a known issue.
The reconnection forced by EtherConn.js sendPoints() function upon receiving an invalid response isn't reliable, as it says in the code:
`if (_this.valid) {
                // console.log('points sent.');
                if (!_this.beginsent) {
                    _this.sendBegin(_this.rate, callback);
                }
                else {
                    callback();
                }
            }
            else {
                
                // When we receive an invalid response, the Ether Dream seems to kinda crash so we need to make a new connection.
                // This is a big, big hack. Need to improve.
                _this.reconnect().then(() => {
                    setTimeout(() => {
                        _this.streamFrames();
                    }, 100);
                });
                throw new Error('Got invalid response from Ether Dream');
            }`
Here's the log of responses:
`SOCKET: Connecting to 192.168.1.234:7765 ...
SOCKET CONNECT: client connected
we got enough input bytes
Standard response:
{
  response: 'a',
  command: '?',
  success: true,
  str: 'resp=a,fullness=0,raw=97,63,0,0,0,0,0,0,3,115,0,0,0,0,0,0,0,0,0,0,0,0',
  status: {
    protocol: 0,
    light_engine_state: 0,
    playback_state: 0,
    source: 0,
    light_engine_flags: 0,
    playback_flags: 29443,
    source_flags: 0,
    buffer_fullness: 0,
    point_rate: 0,
    point_count: 0
  }
}
we got enough input bytes
Standard response:
{
  response: 'I',
  command: 's',
  success: false,
  str: 'resp=I,fullness=0,raw=73,115,0,0,0,0,0,0,3,115,0,0,0,0,0,0,0,0,0,0,0,0',
  status: {
    protocol: 0,
    light_engine_state: 0,
    playback_state: 0,
    source: 0,
    light_engine_flags: 0,
    playback_flags: 29443,
    source_flags: 0,
    buffer_fullness: 0,
    point_rate: 0,
    point_count: 0
  }
}
we got enough input bytes
Parsing response to prepare call
Standard response:
{
  response: 'a',
  command: 'p',
  success: true,
  str: 'resp=a,fullness=0,raw=97,112,0,0,1,0,0,0,1,115,0,0,0,0,0,0,0,0,0,0,0,0',
  status: {
    protocol: 0,
    light_engine_state: 0,
    playback_state: 1,
    source: 0,
    light_engine_flags: 0,
    playback_flags: 29441,
    source_flags: 0,
    buffer_fullness: 0,
    point_rate: 0,
    point_count: 0
  }
}
Send 1799 points to DAC
{
  command: 'd',
  batch: 1799,
  points: [
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 4074, y: 1712, r: 0, g: 0, b: 0 },
    { x: 3722, y: 913, r: 0, g: 0, b: 0 },
    { x: 3371, y: 115, r: 0, g: 0, b: 0 },
    { x: 3018, y: -675, r: 0, g: 21845, b: 65535 },
    { x: 2661, y: -1474, r: 0, g: 21845, b: 65535 },
    { x: 2309, y: -2272, r: 0, g: 21845, b: 65535 },
    { x: 1957, y: -3071, r: 0, g: 21845, b: 65535 },
    { x: 1560, y: -3923, r: 0, g: 21845, b: 65535 },
    { x: 1159, y: -4775, r: 0, g: 21845, b: 65535 },
    { x: 921, y: -5287, r: 0, g: 21845, b: 65535 },
    { x: 581, y: -6159, r: 0, g: 21845, b: 65535 },
    { x: 327, y: -6466, r: 0, g: 21845, b: 65535 },
    { x: -401, y: -7494, r: 0, g: 21845, b: 65535 },
    { x: -401, y: -7494, r: 0, g: 21845, b: 65535 },
    { x: -401, y: -7494, r: 0, g: 21845, b: 65535 },
    { x: -401, y: -7494, r: 0, g: 21845, b: 65535 },
    { x: -401, y: -7494, r: 0, g: 21845, b: 65535 },
    { x: 15, y: -7347, r: 0, g: 21845, b: 65535 },
    { x: 556, y: -7154, r: 0, g: 21845, b: 65535 },
    { x: 1053, y: -6925, r: 0, g: 21845, b: 65535 },
    { x: 1760, y: -6434, r: 0, g: 21845, b: 65535 },
    { x: 2473, y: -5942, r: 0, g: 21845, b: 65535 },
    { x: 2645, y: -5725, r: 0, g: 21845, b: 65535 },
    { x: 3030, y: -5397, r: 0, g: 21845, b: 65535 },
    { x: 3486, y: -4930, r: 0, g: 21845, b: 65535 },
    { x: 3486, y: -4930, r: 0, g: 21845, b: 65535 },
    { x: 3486, y: -4930, r: 0, g: 21845, b: 65535 },
    { x: 3486, y: -4930, r: 0, g: 21845, b: 65535 },
    { x: 3486, y: -4930, r: 0, g: 21845, b: 65535 },
    { x: 3363, y: -4959, r: 0, g: 21845, b: 65535 },
    { x: 3363, y: -4959, r: 0, g: 21845, b: 65535 },
    { x: 3363, y: -4959, r: 0, g: 21845, b: 65535 },
    { x: 3363, y: -4959, r: 0, g: 21845, b: 65535 },
    { x: 3363, y: -4959, r: 0, g: 21845, b: 65535 },
    { x: 3576, y: -4062, r: 0, g: 21845, b: 65535 },
    { x: 3784, y: -3165, r: 0, g: 21845, b: 65535 },
    { x: 3997, y: -2272, r: 0, g: 21845, b: 65535 },
    { x: 4210, y: -1375, r: 0, g: 21845, b: 65535 },
    { x: 4423, y: -478, r: 0, g: 21845, b: 65535 },
    { x: 4636, y: 410, r: 0, g: 21845, b: 65535 },
    { x: 4844, y: 1307, r: 0, g: 21845, b: 65535 },
    { x: 5057, y: 2204, r: 0, g: 21845, b: 65535 },
    { x: 5057, y: 2204, r: 0, g: 21845, b: 65535 },
    { x: 5057, y: 2204, r: 0, g: 21845, b: 65535 },
    { x: 5057, y: 2204, r: 0, g: 21845, b: 65535 },
    { x: 5057, y: 2204, r: 0, g: 21845, b: 65535 },
    { x: 4234, y: 1888, r: 0, g: 21845, b: 65535 },
    { x: 4234, y: 1888, r: 0, g: 21845, b: 65535 },
    { x: 4074, y: 1712, r: 0, g: 21845, b: 65535 },
    { x: 3722, y: 913, r: 0, g: 21845, b: 65535 },
    { x: 3371, y: 115, r: 0, g: 21845, b: 65535 },
    { x: 3018, y: -675, r: 0, g: 21845, b: 65535 },
    { x: 2661, y: -1474, r: 0, g: 0, b: 0 },
    { x: 2309, y: -2272, r: 0, g: 0, b: 0 },
    { x: 1957, y: -3071, r: 0, g: 0, b: 0 },
    { x: 1560, y: -3923, r: 0, g: 0, b: 0 },
    { x: 1159, y: -4775, r: 0, g: 0, b: 0 },
    { x: 1555, y: -4980, r: 0, g: 0, b: 0 },
    { x: 1555, y: -4980, r: 0, g: 0, b: 0 },
    { x: 1555, y: -4980, r: 0, g: 0, b: 0 },
    { x: 1555, y: -4980, r: 0, g: 0, b: 0 },
    { x: 1555, y: -4980, r: 0, g: 0, b: 0 },
    { x: 364, y: -4361, r: 0, g: 21845, b: 65535 },
    { x: -430, y: -3943, r: 0, g: 21845, b: 65535 },
    { x: -1224, y: -3530, r: 0, g: 21845, b: 65535 },
    { x: -2023, y: -3116, r: 0, g: 21845, b: 65535 },
    { x: -2818, y: -2702, r: 0, g: 21845, b: 65535 },
    { x: -2818, y: -2702, r: 0, g: 21845, b: 65535 },
    { x: -2818, y: -2702, r: 0, g: 21845, b: 65535 },
    { x: -3400, y: -2973, r: 0, g: 21845, b: 65535 },
    { x: -3400, y: -2973, r: 0, g: 21845, b: 65535 },
    { x: -3400, y: -2973, r: 0, g: 21845, b: 65535 },
    { x: -3400, y: -2973, r: 0, g: 21845, b: 65535 },
    { x: -3350, y: -3087, r: 0, g: 21845, b: 65535 },
    { x: -2814, y: -3698, r: 0, g: 21845, b: 65535 },
    { x: -2281, y: -4312, r: 0, g: 21845, b: 65535 },
    { x: -1749, y: -4922, r: 0, g: 21845, b: 65535 },
    { x: -1211, y: -5537, r: 0, g: 21845, b: 65535 },
    { x: -680, y: -6151, r: 0, g: 21845, b: 65535 },
    { x: -41, y: -6884, r: 0, g: 21845, b: 65535 },
    { x: -41, y: -6884, r: 0, g: 0, b: 0 },
    { x: -41, y: -6884, r: 0, g: 0, b: 0 },
    { x: -41, y: -6884, r: 0, g: 0, b: 0 },
    { x: -41, y: -6884, r: 0, g: 0, b: 0 },
    { x: -41, y: -6884, r: 0, g: 0, b: 0 },
    { x: -2429, y: -9104, r: 0, g: 0, b: 0 },
    { x: -4600, y: -11123, r: 0, g: 0, b: 0 },
    { x: -6566, y: -12950, r: 0, g: 0, b: 0 },
    { x: -8335, y: -14593, r: 0, g: 0, b: 0 },
    { x: -9920, y: -16063, r: 0, g: 0, b: 0 },
    { x: -11329, y: -17370, r: 0, g: 0, b: 0 },
    { x: -12570, y: -18525, r: 0, g: 0, b: 0 },
    ... 1699 more items
  ]
}
we got enough input bytes
Standard response:
{
  response: 'a',
  command: 'd',
  success: true,
  str: 'resp=a,fullness=1799,raw=97,100,0,0,1,0,0,0,1,115,0,0,7,7,0,0,0,0,0,0,0,0',
  status: {
    protocol: 0,
    light_engine_state: 0,
    playback_state: 1,
    source: 0,
    light_engine_flags: 0,
    playback_flags: 29441,
    source_flags: 0,
    buffer_fullness: 1799,
    point_rate: 0,
    point_count: 0
  }
}
we got enough input bytes
Standard response:
{
  response: 'a',
  command: 'b',
  success: true,
  str: 'resp=a,fullness=1799,raw=97,98,0,0,2,0,0,0,1,115,0,0,7,7,48,117,0,0,0,0,0,0',
  status: {
    protocol: 0,
    light_engine_state: 0,
    playback_state: 2,
    source: 0,
    light_engine_flags: 0,
    playback_flags: 29441,
    source_flags: 0,
    buffer_fullness: 1799,
    point_rate: 30000,
    point_count: 0
  }
}
Sending ping
send ping command
we got enough input bytes
Standard response:
{
  response: 'a',
  command: '?',
  success: true,
  str: 'resp=a,fullness=927,raw=97,63,0,0,2,0,0,0,1,115,0,0,159,3,48,117,0,0,104,3,0,0',
  status: {
    protocol: 0,
    light_engine_state: 0,
    playback_state: 2,
    source: 0,
    light_engine_flags: 0,
    playback_flags: 29441,
    source_flags: 0,
    buffer_fullness: 927,
    point_rate: 30000,
    point_count: 872
  }
}
Send 872 points to DAC
{
  command: 'd',
  batch: 872,
  points: [
    { x: 626, y: -11963, r: 65535, g: 61166, b: 61166 },
    { x: 1200, y: -11283, r: 65535, g: 61166, b: 61166 },
    { x: 1654, y: -10616, r: 65535, g: 61166, b: 61166 },
    { x: 2108, y: -9944, r: 65535, g: 61166, b: 61166 },
    { x: 2264, y: -9522, r: 65535, g: 61166, b: 61166 },
    { x: 2297, y: -9444, r: 65535, g: 61166, b: 61166 },
    { x: 2747, y: -8527, r: 65535, g: 61166, b: 61166 },
    { x: 3182, y: -7433, r: 65535, g: 61166, b: 61166 },
    { x: 3182, y: -7433, r: 0, g: 0, b: 0 },
    { x: 3182, y: -7433, r: 0, g: 0, b: 0 },
    { x: 3182, y: -7433, r: 0, g: 0, b: 0 },
    { x: 3182, y: -7433, r: 0, g: 0, b: 0 },
    { x: 3182, y: -7433, r: 0, g: 0, b: 0 },
    { x: -0, y: -8056, r: 0, g: 0, b: 0 },
    { x: -2912, y: -8629, r: 0, g: 0, b: 0 },
    { x: -5557, y: -9145, r: 0, g: 0, b: 0 },
    { x: -7950, y: -9612, r: 0, g: 0, b: 0 },
    { x: -10105, y: -10038, r: 0, g: 0, b: 0 },
    { x: -12034, y: -10415, r: 0, g: 0, b: 0 },
    { x: -13749, y: -10751, r: 0, g: 0, b: 0 },
    { x: -15261, y: -11046, r: 0, g: 0, b: 0 },
    { x: -16584, y: -11304, r: 0, g: 0, b: 0 },
    { x: -17735, y: -11529, r: 0, g: 0, b: 0 },
    { x: -18718, y: -11721, r: 0, g: 0, b: 0 },
    { x: -19550, y: -11885, r: 0, g: 0, b: 0 },
    { x: -20246, y: -12020, r: 0, g: 0, b: 0 },
    { x: -20815, y: -12131, r: 0, g: 0, b: 0 },
    { x: -21270, y: -12221, r: 0, g: 0, b: 0 },
    { x: -21621, y: -12291, r: 0, g: 0, b: 0 },
    { x: -21888, y: -12344, r: 0, g: 0, b: 0 },
    { x: -22081, y: -12381, r: 0, g: 0, b: 0 },
    { x: -22208, y: -12405, r: 0, g: 0, b: 0 },
    { x: -22286, y: -12422, r: 0, g: 0, b: 0 },
    { x: -22327, y: -12430, r: 0, g: 0, b: 0 },
    { x: -22343, y: -12434, r: 0, g: 0, b: 0 },
    { x: -22343, y: -12434, r: 0, g: 0, b: 0 },
    { x: -22343, y: -12434, r: 0, g: 0, b: 0 },
    { x: -22343, y: -12434, r: 0, g: 0, b: 0 },
    { x: -22343, y: -12434, r: 0, g: 0, b: 0 },
    { x: -22343, y: -12434, r: 0, g: 0, b: 0 },
    { x: -21131, y: -11566, r: 0, g: 65535, b: 61166 },
    { x: -21020, y: -11426, r: 0, g: 65535, b: 61166 },
    { x: -21020, y: -11426, r: 0, g: 65535, b: 61166 },
    { x: -20983, y: -11238, r: 0, g: 65535, b: 61166 },
    { x: -21012, y: -11025, r: 0, g: 65535, b: 61166 },
    { x: -21012, y: -11025, r: 0, g: 65535, b: 61166 },
    { x: -21114, y: -10833, r: 0, g: 65535, b: 61166 },
    { x: -21262, y: -10673, r: 0, g: 65535, b: 61166 },
    { x: -21262, y: -10673, r: 0, g: 65535, b: 61166 },
    { x: -21483, y: -10583, r: 0, g: 65535, b: 61166 },
    { x: -21483, y: -10583, r: 0, g: 0, b: 0 },
    { x: -21483, y: -10583, r: 0, g: 0, b: 0 },
    { x: -21483, y: -10583, r: 0, g: 0, b: 0 },
    { x: -21483, y: -10583, r: 0, g: 0, b: 0 },
    { x: -21483, y: -10583, r: 0, g: 0, b: 0 },
    { x: -21711, y: -8985, r: 0, g: 0, b: 0 },
    { x: -21711, y: -8985, r: 0, g: 0, b: 0 },
    { x: -21711, y: -8985, r: 0, g: 0, b: 0 },
    { x: -21711, y: -8985, r: 0, g: 0, b: 0 },
    { x: -21711, y: -8985, r: 0, g: 0, b: 0 },
    { x: -22556, y: -9661, r: 65535, g: 65535, b: 0 },
    { x: -23117, y: -10112, r: 65535, g: 65535, b: 0 },
    { x: -23887, y: -10796, r: 65535, g: 65535, b: 0 },
    { x: -23990, y: -10943, r: 65535, g: 65535, b: 0 },
    { x: -24112, y: -11111, r: 65535, g: 65535, b: 0 },
    { x: -24112, y: -11111, r: 65535, g: 65535, b: 0 },
    { x: -24166, y: -11357, r: 65535, g: 65535, b: 0 },
    { x: -24166, y: -11357, r: 65535, g: 65535, b: 0 },
    { x: -24166, y: -11357, r: 65535, g: 65535, b: 0 },
    { x: -24166, y: -11357, r: 65535, g: 65535, b: 0 },
    { x: -24166, y: -11357, r: 65535, g: 65535, b: 0 },
    { x: -23596, y: -11021, r: 65535, g: 65535, b: 0 },
    { x: -22638, y: -10742, r: 65535, g: 65535, b: 0 },
    { x: -22638, y: -10742, r: 65535, g: 65535, b: 0 },
    { x: -22638, y: -10742, r: 65535, g: 65535, b: 0 },
    { x: -22413, y: -10878, r: 65535, g: 65535, b: 0 },
    { x: -22413, y: -10878, r: 65535, g: 65535, b: 0 },
    { x: -22413, y: -10878, r: 65535, g: 65535, b: 0 },
    { x: -21446, y: -10595, r: 65535, g: 65535, b: 0 },
    { x: -21446, y: -10595, r: 65535, g: 65535, b: 0 },
    { x: -21446, y: -10595, r: 65535, g: 65535, b: 0 },
    { x: -21286, y: -10308, r: 65535, g: 65535, b: 0 },
    { x: -21286, y: -10308, r: 0, g: 0, b: 0 },
    { x: -21286, y: -10308, r: 0, g: 0, b: 0 },
    { x: -21286, y: -10308, r: 0, g: 0, b: 0 },
    { x: -21286, y: -10308, r: 0, g: 0, b: 0 },
    { x: -21286, y: -10308, r: 0, g: 0, b: 0 },
    { x: -23609, y: -10849, r: 0, g: 0, b: 0 },
    { x: -23940, y: -10927, r: 0, g: 0, b: 0 },
    { x: -23940, y: -10927, r: 0, g: 0, b: 0 },
    { x: -23940, y: -10927, r: 0, g: 0, b: 0 },
    { x: -23940, y: -10927, r: 0, g: 0, b: 0 },
    { x: -23940, y: -10927, r: 0, g: 0, b: 0 },
    { x: -24088, y: -10972, r: 65535, g: 61166, b: 61166 },
    { x: -24715, y: -11283, r: 65535, g: 61166, b: 61166 },
    { x: -24715, y: -11283, r: 65535, g: 61166, b: 61166 },
    { x: -24932, y: -11582, r: 65535, g: 61166, b: 61166 },
    { x: -24932, y: -11582, r: 65535, g: 61166, b: 61166 },
    { x: -24968, y: -11766, r: 65535, g: 61166, b: 61166 },
    { x: -24997, y: -12090, r: 65535, g: 61166, b: 61166 },
    ... 772 more items
  ]
}
we got enough input bytes
Standard response:
{
  response: 'I',
  command: 'd',
  success: false,
  str: 'resp=I,fullness=0,raw=73,100,0,0,0,0,0,0,3,115,0,0,0,0,0,0,0,0,0,0,0,0',
  status: {
    protocol: 0,
    light_engine_state: 0,
    playback_state: 0,
    source: 0,
    light_engine_flags: 0,
    playback_flags: 29443,
    source_flags: 0,
    buffer_fullness: 0,
    point_rate: 0,
    point_count: 0
  }
}
SOCKET: Connecting to 192.168.1.234:7765 ...
Error: Got invalid response from Ether Dream
    at Object.callback (C:\Users\turnn\Desktop\Projects\laser\LaserDac\node_modules\@laser-dac\ether-dream\dist\EtherConn.js:222:23)
    at EtherConn._popinputqueue (C:\Users\turnn\Desktop\Projects\laser\LaserDac\node_modules\@laser-dac\ether-dream\dist\EtherConn.js:32:25)
    at Timeout._onTimeout (C:\Users\turnn\Desktop\Projects\laser\LaserDac\node_modules\@laser-dac\ether-dream\dist\EtherConn.js:69:26)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
[ERROR] 18:00:19 Error: Got invalid response from Ether Dream`

You'll notice the invalid response to the data stream, I can't really see any fault in the data stream itself, it is interesting it is always proceeded by a ping request? I'll probably try remove the ping request next...

**Comment by SpaceK33z** [comment]
Hey, we actually had the exact same issue and unfortunately we also didn't find a fix yet. I've not been working on it for a long time so at the moment I don't have any more info unfortunately. If you do get a workaround we'll gladly merge a PR.

**Comment by sebleedelisle** [comment]
Hi there, I hope you don't mind me jumping in but I have some experience coding the Etherdream protocol (see github.com/sebleedelisle/ofxLaser ) so perhaps I can help? 

The reason the Etherdream returned the invalid 'I' response is because it ran out of points and switched off output (the playback flags underflow bit is set). This is likely due to intermittent latency in the network (or dropped packets etc),  and is expected behaviour (and actually probably desirable for safety reasons). 

The way to get around it is to : 
* check that the playback_state is PLAY_BACK_IDLE and the light_engine_state is LIGHT_ENGINE_READY  (if the light_engine_state is in ESTOP you'll also need to send the clear command)
* resend the "prepare" command ('p'); 
* start sending points again
* send the "begin" command ('b')

You shouldn't need to reconnect the TCP connection at all. 

I hope this helps, you can see my c++ code for doing this in the ofxLaser codebase. I've rewritten the etherdream c library from scratch so I feel like I know it quite well now. 

Let me know if I can help any other way.

Seb

**Comment by SpaceK33z** [comment]
@sebleedelisle thanks so much, that is really insightful! When we were making Modulaser we were debugging this issue for weeks. I don't have time myself to fix & test this soon (we're very busy on a sprint to launch a new app).

If either of you want to fix this & send a PR I can offer a free Modulaser license in return.

**Comment by turnn** [comment]
Awesome! Thanks for the detailed reply @sebleedelisle , @SpaceK33z we'll give the recommendations a try but it might be a couple weeks as this is just a side project for us

**Comment by turnn** [comment]
Hey guys, I spent a couple days on it and it's still not stable, I believe the problem is that the library only sends enough points to fill the DAC's buffer. I may be incorrect but I think @sebleedelisle 's library works by sending points at the point rate, instead of trying to fill the buffer. I tried to do this and it was significantly better but still quite unstable i.e. 10 underflows a minute instead of an underflow every second. We'll probably try ofxlaser next, but may be back as we did want a JS library.

**Comment by sebleedelisle** [comment]
Ah a few things to unpick here... if you're constantly getting buffer under-runs either your code isn't getting updated enough or your network isn't fast enough to accommodate the traffic. 

A few things to check... 
* I assume you're not running over wifi? 
* Have you tried reducing the point rate? I find a sweet spot is around 30000 pps
* Have you checked how often the comms code is running? In my library I'm running it on a different thread which makes it somewhat easier. I'm constantly pinging the etherdream so I always have an up to date report on the buffer fullness. I'm not sure how much control you have over the timing of this kind of thing in node.js. 

If I was you I would try filling up the buffer every time you send points, the timing should be more forgiving that way. I don't really understand why you're getting more errors when you try filling up the buffer, unless you're over-filing it? Have you checked the buffer size? You should get that back from the etherdream in the broadcast packets. (Note that etherdream 1 and 2 have different buffer sizes). 

So a few things for you to check, good luck! 

Seb

**Comment by dinther** [comment]
Hey guys, You're all miles ahead of me with the knowledge you have build up around the lasercube network protocol. I only just received my lasercube pro but immediately I noticed its pretty heavy handed on my network. I had converted some simple video animations into an svg sequence and via wifi things didn't run too smoothly.

Am I correct in my understanding that the app is constantly resending the same points over and over for a static image?
I had assumed communication at application level would have been higher level with the cube capable to keep state.
